apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cat-app
spec:
  ingressClassName:
  rules:
    - host: cat-app.k3d.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cat-app
                port:
                  number: 80