apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-system
  labels:
    name: cnpg-system
spec:
  project: default
  source:
    repoURL: https://github.com/jonnyhoeven/media-k3s.git
    targetRevision: HEAD
    path: namespace/cnpg-system
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 5